### PR TITLE
Document processes and fix bugs

### LINKED ISSUE #9: Write documentation for users

### PR DESCRIPTION
**Pull request by kosyfrances**
Fixes #9

This PR documents processes for users, and fixes bugs.
It switches to using a config flag as a more flexible option for users. This is because on Zabbix server, the home directory is different (i.e /var/lib/zabbix) when Zabbix calls the script on it's web UI during remote action.
It writes logs to file for production use as well as stdout.

More information is on the readme.

### CODE REVIEW

File: cli/main.go [hunk 1]
```diff
@@ -1,7 +1,25 @@
...
+import (
+	"io"
+	"os"
+
+	"github.com/sirupsen/logrus"
+
+	"github.com/kosyfrances/rundeck-zabbix/cli/cmd"
+)
+
+const logFile = "/tmp/rundeck-zabbix.log"
```
Comment (osule) [inline cli/main.go]: How about running in WIN systems?
What do you think of having the log path to be in the same folder as the built binary?

File: README.md [hunk 2]
```diff
@@ -1,3 +1,90 @@
...
+
+To map Zabbix hosts to Rundeck nodes, run the following to generate a `resources.yml` template and modify as appropriate. You can read more about [node entries here](https://docs.rundeck.com/docs/man5/resource-yaml.html) and format yours appropriately.
+
+```bash
+rundeck-zabbix generate resources --config=/path/to/dir/.config.json
+```
+Do not forget to add Rundeck’s local host to `resources.yml` file. Copy the file over to `/etc/rundeck/projects/project_name/resources.yml` or `/var/rundeck/projects/project_name/resources.yml` on Rundeck’s server.
+
+### Generate Rundeck jobs template
+To map Zabbix triggers to Rundeck jobs, run the following to generate a `jobs.yml` template and modify as appropriate. Update the `commands` section with the appropriate command you want Rundeck to execute. . You can read more about [job entries here](https://docs.rundeck.com/docs/man5/job-yaml.html) and format yours appropriately.
```
Comment (osule) [inline README.md]: 💅 ~execute. .~ execute.

File: cli/main.go (hunk 1 above)
Comment (kosyfrances) [reply cli/main.go]: I've not thought of WIN systems yet. Maybe that can be an added feature later on? At the moment the focus is on Linux. About the same folder as the built binary, not sure how to track that either.

File: README.md [hunk 3]
```diff
@@ -1,3 +1,90 @@
...
-Runbook Automation integration with Zabbix and Rundeck based on https://kosyfrances.github.io/rundeck-zabbix/
-Using Zabbix API v4.0 and Rundeck API v30
+rundeck-zabbix is a Runbook automation tool, that integrates Zabbix trigger-based actions into Rundeck. It is based on https://kosyfrances.github.io/rundeck-zabbix/ and built with Zabbix API v4.2 and Rundeck API v30.
+
+**Basic flow:**
+
+* A service stops running
+* Zabbix fires trigger
+* Zabbix action calls rundeck-zabbix
+* rundeck-zabbix executes job on Rundeck
```
[the remark this answers is not in the document]
Comment (kosyfrances) [reply README.md]: The whole flow is based on this [article](https://assets.zabbix.com/files/zabconf2016/wolfgang_alper_IntelliTrend-Zabbix-Meets-Ops-With-Rundeck.pdf) and the summary is more of the following:
```
Map Zabbix host to Rundeck nodes.
Map Zabbix trigger names to Rundeck job names.
On trigger event, pass related host and trigger from Zabbix to Rundeck.
Bonus: Return job execution status from Rundeck as an event acknowledgment in Zabbix
```

On one hand, it's more of, when the event is acknowledged, the assumption is that something was done about it. On the other hand, it's a good idea to let Ops know that something is being done at the moment .... In this case, it is possible for the Ops team to know that the remote command specified, was executed for the trigger on the UI. 
Screenshot 2019-05-01 at 9 40 42 PM

File: cli/cmd/root.go [hunk 4]
```diff
@@ -31,24 +31,22 @@ func Execute() {
...
 func initConfig() {
-	if cfgFile != "" { // enable ability to specify config file via flag
+	if cfgFile != "" {
+		// enable ability to specify config file via flag
 		viper.SetConfigFile(cfgFile)
 	}
 
 	// setup config file with defaults
-	if lib.FileExists(lib.ConfigPath) == false {
+	if !lib.FileExists(cfgFile) {
```
[the remark this answers is not in the document]
Comment (kosyfrances) [reply cli/cmd/root.go]: If it errors, how about in cases when setup needs to be run? 🤔

[the remark this answers is not in the document]
Comment (kosyfrances) [reply cli/cmd/root.go]: Fixed in updated push.

**Comment by kosyfrances** [comment]
I forgot to say this is ready for another review :)

File: cli/main.go (hunk 1 above)
Comment (tundeaoni) [reply cli/main.go]: This can be configurable with a  specified default but this is a decent place to start and subsequently iterate

File: cli/cmd/root.go [hunk 5]
```diff
@@ -31,30 +31,30 @@ func Execute() {
...
 
-	// setup config file with defaults
-	if lib.FileExists(lib.ConfigPath) == false {
-		// only warn when not running setup command
-		log.Warn("Configuration file not found. Please setup using `setup` command")
-	} else {
-		viper.SetConfigName(lib.AppConfigName)   // name of config file (without extension)
-		viper.AddConfigPath(lib.ConfigDirectory) // adding home directory as first search path
-		viper.AutomaticEnv()                     // read in environment variables that match
+	if lib.FileExists(cfgFile) {
```
Comment (tundeaoni) [inline cli/cmd/root.go]: if file doesn't exist && setupCmd.CalledAs() == "" throw the error else load configuration

File: cli/cmd/root.go [hunk 6]
```diff
@@ -31,30 +31,30 @@ func Execute() {
...
+		viper.AutomaticEnv() // read in environment variables that match
 
 		// If a config file is found, read it in.
 		if err := viper.ReadInConfig(); err == nil {
 			log.Info("Loading config file:", viper.ConfigFileUsed())
 		}
-
+	} else if setupCmd.CalledAs() != "" {
```
Comment (osule) [inline cli/cmd/root.go]: This seems like an issue isn't been addressed.
 Why does this error?

File: cli/cmd/setup.go [hunk 7]
```diff
@@ -40,9 +39,9 @@ func init() {
 }
 
 func runSetup(cmd *cobra.Command, args []string) {
-	cfg, err := lib.NewConfigFromFile(lib.ConfigPath)
+	cfg, err := lib.NewConfigFromFile(cfgFile)
 	if err != nil {
-		log.Infof("no config file yet. %v", err)
+		log.Info("no config file yet.")
```
Comment (osule) [inline cli/cmd/setup.go]: When user runs the setup command and it fails to create a configuration file; 
I wouldn't find just logging the information and carrying on enough here.
Better to log an error and log information about what default configuration the program uses with sensitive ones redacted.

File: README.md [hunk 8]
```diff
@@ -1,3 +1,90 @@
...
+
+### Generate Rundeck resources template
+Rundeck uses a resource document to declare the resource models used by a project to define the set of Nodes that are available. This file is usually found in `/etc/rundeck/projects/project_name/` or `/var/rundeck/projects/project_name` in the Rundeck server.
+
+To map Zabbix hosts to Rundeck nodes, run the following to generate a `resources.yml` template and modify as appropriate. You can read more about [node entries here](https://docs.rundeck.com/docs/man5/resource-yaml.html) and format yours appropriately.
+
+```bash
+rundeck-zabbix generate resources --config=/path/to/dir/.config.json
+```
+Do not forget to add Rundeck’s local host to `resources.yml` file. Copy the file over to `/etc/rundeck/projects/project_name/resources.yml` or `/var/rundeck/projects/project_name/resources.yml` on Rundeck’s server.
```
[the remark this answers is not in the document]
Comment (kosyfrances) [reply README.md]: By default in projects, Rundeck has a definition of it's own local node as a resource. Rundeck users will probably understand this part. Will try to rephrase it properly.

File: cli/cmd/setup.go (hunk 7 above)
Comment (kosyfrances) [reply cli/cmd/setup.go]: fixed in updated push

File: cli/cmd/root.go (hunk 6 above)
Comment (kosyfrances) [reply cli/cmd/root.go]: fixed in updated push

File: README.md [hunk 9]
```diff
@@ -1,3 +1,90 @@
...
+
+Then build with:
+```bash
+make build
+```
+Run `rundeck-zabbix help` to get list of available commands.
+
+### Initialise tool configuration
+You'd need the following information:
+* Zabbix Server URL in the form of `ZABBIXURL/api_jsonrpc.php`
```
[the remark this answers is not in the document]
Comment (kosyfrances) [reply README.md]: fixed in updated push

File: README.md [hunk 10]
```diff
@@ -1,3 +1,90 @@
...
+* Zabbix username and password (required to generate Zabbix API key)
+* Rundeck URL
+* Rundeck API key (usually gotten from `RUNDECK_URL:PORT_NUMBER/user/profile`)
```
[the remark this answers is not in the document]
Comment (kosyfrances) [reply README.md]: fixed in updated push

**Comment by kosyfrances** [comment]
Ready for another review :)
